services:
    redis:
        hostname: "cache_redis"
        container_name: "cache_redis"
        image: "redis:7.0-alpine"
        ports:
        - "6379:6379"
        networks:
        - worker
        volumes:
        - ./volume/redis:/data
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]


networks:
    worker:
        driver: bridge
        name: worker_network
